name: Sync to Hugging Face Space
on:
  push:
    branches: [main] # Runs every time you push to main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Replace YOUR_HF_USERNAME and YOUR_SPACE_NAME below
          git push --force https://chiragatrey70:$HF_TOKEN@huggingface.co/spaces/chiragatrey70/interviewai-backend-ML main